# Clock is generated by Zynq PS (FCLK_CLK0, default 100MHz)
# No create_clock needed - Vivado auto-derives it from the PS configuration

# If you want to overconstrain for benchmarking, uncomment and adjust:
# create_clock -period 8.000 -name pl_clk0 [get_pins system_i/zynq_ps/inst/pl_clk0]
